In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("carvana.csv")

In [4]:
df

                            Name   Year  Miles  Price
0                 Chevrolet Trax   2018  41946  16990
1                    GMC Terrain   2020  45328  23990
2                  Jeep Wrangler   2012  81068  21590
3                  Jeep Renegade   2019  35372  21590
4                          BMW X  20173  68992  22990
...                          ...    ...    ...    ...
21995               Honda Accord   2014  98085  17590
21996              Dodge Charger   2016  62616  23990
21997                Ford Taurus   2013  50345  16990
21998   Toyota Corolla Hatchback   2020  27945  23990
21999                Honda Civic   2012  70676  14990

[22000 rows x 4 columns]

In [6]:
df.head()

              Name   Year  Miles  Price
0   Chevrolet Trax   2018  41946  16990
1      GMC Terrain   2020  45328  23990
2    Jeep Wrangler   2012  81068  21590
3    Jeep Renegade   2019  35372  21590
4            BMW X  20173  68992  22990

In [11]:
# Filter the year more than 2025
df_filtered = df[df["Year"] > 2025]

In [9]:
df_filtered

                       Name     Year   Miles  Price
4                     BMW X    20173   68992  22990
31      Mitsubishi Mirage G    20194   24065  15990
34                MAZDA CX-    20165   66644  18590
39              MAZDA MAZDA    20133  100316  12990
46                    FIAT   2013500   44087  15990
...                     ...      ...     ...    ...
21952                 BMW X    20151   35706  22990
21963       MAZDA MX- Miata    20165   42003  22590
21970           MAZDA MAZDA    20123   89624  13990
21975                 BMW X    20151   35706  22990
21981             MAZDA CX-    20155   31686  21990

[2851 rows x 4 columns]

In [12]:
df["Year"].min()

2009

In [13]:
df["Year"].max()

20223500

In [15]:
df["Year"] = df["Year"].astype(str).str[:4].astype(int)

In [16]:
df.head()

              Name  Year  Miles  Price
0   Chevrolet Trax  2018  41946  16990
1      GMC Terrain  2020  45328  23990
2    Jeep Wrangler  2012  81068  21590
3    Jeep Renegade  2019  35372  21590
4            BMW X  2017  68992  22990

In [17]:
df["Year"].max()

2023

In [18]:
df["Miles"].min()

53

In [22]:
df["Miles"].max()

120167

In [23]:
# Standardize Miles Column
from sklearn.preprocessing import StandardScaler

In [25]:
# Here we are Creating the Scaler
sclaer = StandardScaler()

In [26]:
df["Miles"] = sclaer.fit_transform(df[["Miles"]])

In [27]:
df.head()

              Name  Year     Miles  Price
0   Chevrolet Trax  2018 -0.486647  16990
1      GMC Terrain  2020 -0.354977  23990
2    Jeep Wrangler  2012  1.036478  21590
3    Jeep Renegade  2019 -0.742591  21590
4            BMW X  2017  0.566327  22990

In [31]:
#get mean and standard deviation
mean = sclaer.mean_[0]
std_dev = sclaer.scale_[0]

In [34]:
print("Mean value is:::",mean)
print("Standard Deviation:::", std_dev)

Mean value is::: 54445.69731818182
Standard Deviation::: 25685.350148367597

In [35]:
#Label Encoding for the Name Colum
from sklearn.preprocessing import LabelEncoder

In [36]:
#Creating Instance for the Label Encoder
le = LabelEncoder()

In [39]:
df["Name_encoded"] = le.fit_transform(df["Name"])

In [40]:
df.head()

              Name  Year     Miles  Price  Name_Encoded  Name_encoded
0   Chevrolet Trax  2018 -0.486647  16990            71            71
1      GMC Terrain  2020 -0.354977  23990           127           127
2    Jeep Wrangler  2012  1.036478  21590           195           195
3    Jeep Renegade  2019 -0.742591  21590           193           193
4            BMW X  2017  0.566327  22990            20            20

In [41]:
X = df[["Year","Miles","Name_encoded"]]
y = df["Price"]

In [42]:
X

       Year     Miles  Name_encoded
0      2018 -0.486647            71
1      2020 -0.354977           127
2      2012  1.036478           195
3      2019 -0.742591           193
4      2017  0.566327            20
...     ...       ...           ...
21995  2014  1.698996           132
21996  2016  0.318092            80
21997  2013 -0.159651           116
21998  2020 -1.031744           359
21999  2012  0.631889           138

[22000 rows x 3 columns]

In [43]:
y

0        16990
1        23990
2        21590
3        21590
4        22990
         ...
21995    17590
21996    23990
21997    16990
21998    23990
21999    14990
Name: Price, Length: 22000, dtype: int64

In [44]:
#Random Forest Regressor for taking Decision
from sklearn.ensemble import RandomForestRegressor

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [47]:
len(X_train)

17600

In [49]:
len(X_test)

4400

In [53]:
model = RandomForestRegressor(n_estimators=100,random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [54]:
#Predict and evaluate
from sklearn.metrics import mean_absolute_error, r2_score

In [56]:
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Absolute Error :::${mae:.2f}")
print(f"R score is::: ${r2:.3f}")

Mean Absolute Error :::$913.11
R score is::: $0.858

In [57]:
import coremltools as ct

In [58]:
coreml_model = ct.converters.sklearn.convert(model, ["Year","Miles","Name_encoded"],"Price")

In [62]:
coreml_model.author = "Nishanth"
coreml_model.license = "MIT"
coreml_model.short_description = "Predict the used car prices based on the year and mile and name"
coreml_model.version = "1.0.0"

In [63]:
coreml_model.save("Carvana.mlmodel")

In [70]:
car_name_mapping = {name: code for name, code in zip (le.classes_, le.transform(le.classes_)) }

In [71]:
car_name_mapping

{' Acura ILX': 0,
 ' Acura MDX': 1,
 ' Acura MDX Sport Hybrid': 2,
 ' Acura RDX': 3,
 ' Acura RLX': 4,
 ' Acura TL': 5,
 ' Acura TLX': 6,
 ' Acura TSX': 7,
 ' Alfa Romeo C Spider': 8,
 ' Alfa Romeo Giulia': 9,
 ' Alfa Romeo Stelvio': 10,
 ' Audi A': 11,
 ' Audi A Sportback e-tron': 12,
 ' Audi Q': 13,
 ' Audi S': 14,
 ' Audi TT': 15,
 ' Audi allroad': 16,
 ' Audi e-tron': 17,
 ' BMW  Series': 18,
 ' BMW M': 19,
 ' BMW X': 20,
 ' BMW Z': 21,
 ' BMW i': 22,
 ' Buick Cascada': 23,
 ' Buick Enclave': 24,
 ' Buick Encore': 25,
 ' Buick Encore GX': 26,
 ' Buick Envision': 27,
 ' Buick LaCrosse': 28,
 ' Buick Lucerne': 29,
 ' Buick Regal': 30,
 ' Buick Regal Sportback': 31,
 ' Buick Verano': 32,
 ' Cadillac ATS': 33,
 ' Cadillac CT': 34,
 ' Cadillac CTS': 35,
 ' Cadillac DTS': 36,
 ' Cadillac ELR': 37,
 ' Cadillac Escalade ESV': 38,
 ' Cadillac SRX': 39,
 ' Cadillac XT': 40,
 ' Cadillac XTS': 41,
 ' Chevrolet Blazer': 42,
 ' Chevrolet Bolt EV': 43,
 ' Chevrolet Camaro': 44,
 ' Chevrolet Captiva Sport': 45,
 ' Chevrolet City Express': 46,
 ' Chevrolet Colorado Crew Cab': 47,
 ' Chevrolet Colorado Extended Cab': 48,
 ' Chevrolet Corvette': 49,
 ' Chevrolet Cruze': 50,
 ' Chevrolet Cruze Limited': 51,
 ' Chevrolet Equinox': 52,
 ' Chevrolet Impala': 53,
 ' Chevrolet Impala Limited': 54,
 ' Chevrolet Malibu': 55,
 ' Chevrolet Malibu Limited': 56,
 ' Chevrolet Silverado  Crew Cab': 57,
 ' Chevrolet Silverado  Double Cab': 58,
 ' Chevrolet Silverado  HD Crew Cab': 59,
 ' Chevrolet Silverado  HD Regular Cab': 60,
 ' Chevrolet Silverado  Limited Crew Cab': 61,
 ' Chevrolet Silverado  Regular Cab': 62,
 ' Chevrolet Sonic': 63,
 ' Chevrolet Spark': 64,
 ' Chevrolet Spark EV': 65,
 ' Chevrolet Suburban': 66,
 ' Chevrolet Suburban ': 67,
 ' Chevrolet Tahoe': 68,
 ' Chevrolet Trailblazer': 69,
 ' Chevrolet Traverse': 70,
 ' Chevrolet Trax': 71,
 ' Chevrolet Volt': 72,
 ' Chrysler ': 73,
 ' Chrysler Pacifica': 74,
 ' Chrysler Sebring': 75,
 ' Chrysler Town & Country': 76,
 ' Chrysler Voyager': 77,
 ' Dodge Avenger': 78,
 ' Dodge Challenger': 79,
 ' Dodge Charger': 80,
 ' Dodge Dart': 81,
 ' Dodge Durango': 82,
 ' Dodge Grand Caravan Passenger': 83,
 ' Dodge Journey': 84,
 ' FIAT ': 85,
 ' FIAT  Abarth': 86,
 ' FIAT  Spider': 87,
 ' FIAT L': 88,
 ' FIAT X': 89,
 ' FIAT c Abarth': 90,
 ' Ford Bronco': 91,
 ' Ford Bronco Sport': 92,
 ' Ford C-MAX Energi': 93,
 ' Ford C-MAX Hybrid': 94,
 ' Ford EcoSport': 95,
 ' Ford Edge': 96,
 ' Ford Escape': 97,
 ' Ford Expedition': 98,
 ' Ford Expedition EL': 99,
 ' Ford Expedition MAX': 100,
 ' Ford Explorer': 101,
 ' Ford F Lightning': 102,
 ' Ford F Regular Cab': 103,
 ' Ford F Super Cab': 104,
 ' Ford F SuperCrew Cab': 105,
 ' Ford Fiesta': 106,
 ' Ford Flex': 107,
 ' Ford Focus': 108,
 ' Ford Focus ST': 109,
 ' Ford Fusion': 110,
 ' Ford Fusion Energi': 111,
 ' Ford Maverick': 112,
 ' Ford Mustang': 113,
 ' Ford Mustang MACH-E': 114,
 ' Ford Ranger SuperCrew': 115,
 ' Ford Taurus': 116,
 ' Ford Transit  Wagon': 117,
 ' Ford Transit Connect Passenger': 118,
 ' Ford Transit Connect Passenger Wagon': 119,
 ' GMC Acadia': 120,
 ' GMC Acadia Limited': 121,
 ' GMC Canyon Crew Cab': 122,
 ' GMC Sierra  Crew Cab': 123,
 ' GMC Sierra  Double Cab': 124,
 ' GMC Sierra  Limited Crew Cab': 125,
 ' GMC Sierra  Regular Cab': 126,
 ' GMC Terrain': 127,
 ' GMC Yukon': 128,
 ' GMC Yukon XL': 129,
 ' GMC Yukon XL ': 130,
 ' Genesis G': 131,
 ' Honda Accord': 132,
 ' Honda Accord Crosstour': 133,
 ' Honda Accord Hybrid': 134,
 ' Honda CR-V': 135,
 ' Honda CR-V Hybrid': 136,
 ' Honda CR-Z': 137,
 ' Honda Civic': 138,
 ' Honda Civic Type R': 139,
 ' Honda Clarity Plug-in Hybrid': 140,
 ' Honda Crosstour': 141,
 ' Honda Fit': 142,
 ' Honda HR-V': 143,
 ' Honda Insight': 144,
 ' Honda Odyssey': 145,
 ' Honda Passport': 146,
 ' Honda Pilot': 147,
 ' Honda Ridgeline': 148,
 ' Hyundai Accent': 149,
 ' Hyundai Azera': 150,
 ' Hyundai Elantra': 151,
 ' Hyundai Elantra GT': 152,
 ' Hyundai Equus': 153,
 ' Hyundai Genesis': 154,
 ' Hyundai Genesis Coupe': 155,
 ' Hyundai IONIQ ': 156,
 ' Hyundai Ioniq Electric': 157,
 ' Hyundai Ioniq Hybrid': 158,
 ' Hyundai Ioniq Plug-in Hybrid': 159,
 ' Hyundai Kona': 160,
 ' Hyundai Palisade': 161,
 ' Hyundai Santa Cruz': 162,
 ' Hyundai Santa Fe': 163,
 ' Hyundai Santa Fe Sport': 164,
 ' Hyundai Sonata': 165,
 ' Hyundai Sonata Hybrid': 166,
 ' Hyundai Sonata Plug-in Hybrid': 167,
 ' Hyundai Tucson': 168,
 ' Hyundai Tucson Hybrid': 169,
 ' Hyundai Veloster': 170,
 ' Hyundai Venue': 171,
 ' Hyundai Veracruz': 172,
 ' INFINITI EX': 173,
 ' INFINITI FX': 174,
 ' INFINITI G': 175,
 ' INFINITI JX': 176,
 ' INFINITI M': 177,
 ' INFINITI Q': 178,
 ' INFINITI QX': 179,
 ' Jaguar E-PACE': 180,
 ' Jaguar F-PACE': 181,
 ' Jaguar F-TYPE': 182,
 ' Jaguar XE': 183,
 ' Jaguar XF': 184,
 ' Jaguar XJ': 185,
 ' Jeep Cherokee': 186,
 ' Jeep Compass': 187,
 ' Jeep Gladiator': 188,
 ' Jeep Grand Cherokee': 189,
 ' Jeep Grand Cherokee L': 190,
 ' Jeep Liberty': 191,
 ' Jeep Patriot': 192,
 ' Jeep Renegade': 193,
 ' Jeep Wagoneer': 194,
 ' Jeep Wrangler': 195,
 ' Jeep Wrangler Unlimited': 196,
 ' Kia Cadenza': 197,
 ' Kia Carnival': 198,
 ' Kia EV': 199,
 ' Kia Forte': 200,
 ' Kia Forte Koup': 201,
 ' Kia K': 202,
 ' Kia Niro': 203,
 ' Kia Niro EV': 204,
 ' Kia Optima': 205,
 ' Kia Optima Hybrid': 206,
 ' Kia Rio': 207,
 ' Kia Sedona': 208,
 ' Kia Seltos': 209,
 ' Kia Sorento': 210,
 ' Kia Sorento Hybrid': 211,
 ' Kia Sorento Plug-in Hybrid': 212,
 ' Kia Soul': 213,
 ' Kia Soul EV': 214,
 ' Kia Sportage': 215,
 ' Kia Stinger': 216,
 ' Kia Telluride': 217,
 ' Land Rover Discovery': 218,
 ' Land Rover Discovery Sport': 219,
 ' Land Rover LR': 220,
 ' Land Rover Range Rover': 221,
 ' Land Rover Range Rover Evoque': 222,
 ' Land Rover Range Rover Sport': 223,
 ' Land Rover Range Rover Velar': 224,
 ' Lexus CT': 225,
 ' Lexus ES': 226,
 ' Lexus GS': 227,
 ' Lexus GX': 228,
 ' Lexus HS': 229,
 ' Lexus IS': 230,
 ' Lexus LC': 231,
 ' Lexus LS': 232,
 ' Lexus NX': 233,
 ' Lexus RC': 234,
 ' Lexus RX': 235,
 ' Lexus UX': 236,
 ' Lincoln Corsair': 237,
 ' Lincoln MKC': 238,
 ' Lincoln MKS': 239,
 ' Lincoln MKX': 240,
 ' Lincoln MKZ': 241,
 ' Lincoln Nautilus': 242,
 ' Lincoln Navigator': 243,
 ' Lincoln Town Car': 244,
 ' MAZDA CX-': 245,
 ' MAZDA MAZDA': 246,
 ' MAZDA MX- Miata': 247,
 ' MAZDA MX- Miata RF': 248,
 ' MAZDA Tribute': 249,
 ' MINI Clubman': 250,
 ' MINI Convertible': 251,
 ' MINI Countryman': 252,
 ' MINI Coupe': 253,
 ' MINI Hardtop': 254,
 ' MINI Hardtop  Door': 255,
 ' MINI Paceman': 256,
 ' MINI Roadster': 257,
 ' Maserati Ghibli': 258,
 ' Maserati GranTurismo': 259,
 ' Maserati Levante': 260,
 ' Maserati Quattroporte': 261,
 ' Mercedes-Benz A-Class': 262,
 ' Mercedes-Benz B-Class': 263,
 ' Mercedes-Benz C-Class': 264,
 ' Mercedes-Benz CLA': 265,
 ' Mercedes-Benz CLA-Class': 266,
 ' Mercedes-Benz CLK-Class': 267,
 ' Mercedes-Benz CLS-Class': 268,
 ' Mercedes-Benz E-Class': 269,
 ' Mercedes-Benz GLA': 270,
 ' Mercedes-Benz GLA-Class': 271,
 ' Mercedes-Benz GLB': 272,
 ' Mercedes-Benz GLC': 273,
 ' Mercedes-Benz GLE': 274,
 ' Mercedes-Benz GLK-Class': 275,
 ' Mercedes-Benz GLS': 276,
 ' Mercedes-Benz M-Class': 277,
 ' Mercedes-Benz Mercedes-AMG C-Class': 278,
 ' Mercedes-Benz Mercedes-AMG GLC': 279,
 ' Mercedes-Benz Mercedes-AMG GLE Coupe': 280,
 ' Mercedes-Benz Mercedes-AMG SLC': 281,
 ' Mercedes-Benz R-Class': 282,
 ' Mercedes-Benz S-Class': 283,
 ' Mercedes-Benz SL': 284,
 ' Mercedes-Benz SL-Class': 285,
 ' Mercedes-Benz SLC': 286,
 ' Mercedes-Benz SLK-Class': 287,
 ' Mitsubishi Eclipse Cross': 288,
 ' Mitsubishi Lancer': 289,
 ' Mitsubishi Mirage': 290,
 ' Mitsubishi Mirage G': 291,
 ' Mitsubishi Outlander': 292,
 ' Mitsubishi Outlander PHEV': 293,
 ' Mitsubishi Outlander Sport': 294,
 ' Mitsubishi i-MiEV': 295,
 ' Nissan Altima': 296,
 ' Nissan Armada': 297,
 ' Nissan Frontier Crew Cab': 298,
 ' Nissan Frontier King Cab': 299,
 ' Nissan JUKE': 300,
 ' Nissan Kicks': 301,
 ' Nissan LEAF': 302,
 ' Nissan Maxima': 303,
 ' Nissan Murano': 304,
 ' Nissan Pathfinder': 305,
 ' Nissan Quest': 306,
 ' Nissan Rogue': 307,
 ' Nissan Rogue Select': 308,
 ' Nissan Rogue Sport': 309,
 ' Nissan Sentra': 310,
 ' Nissan TITAN XD Crew Cab': 311,
 ' Nissan Titan Crew Cab': 312,
 ' Nissan Versa': 313,
 ' Nissan Versa Note': 314,
 ' Nissan Xterra': 315,
 ' Nissan Z': 316,
 ' Polestar ': 317,
 ' Pontiac Solstice': 318,
 ' Porsche ': 319,
 ' Porsche  Cayman': 320,
 ' Porsche Boxster': 321,
 ' Porsche Cayenne': 322,
 ' Porsche Macan': 323,
 ' Porsche Panamera': 324,
 ' Ram  Classic Crew Cab': 325,
 ' Ram  Classic Quad Cab': 326,
 ' Ram  Classic Regular Cab': 327,
 ' Ram  Crew Cab': 328,
 ' Ram  Quad Cab': 329,
 ' Ram  Regular Cab': 330,
 ' Saturn SKY': 331,
 ' Scion FR-S': 332,
 ' Scion iA': 333,
 ' Scion iM': 334,
 ' Scion iQ': 335,
 ' Scion tC': 336,
 ' Scion xB': 337,
 ' Scion xD': 338,
 ' Subaru Ascent': 339,
 ' Subaru BRZ': 340,
 ' Subaru Crosstrek': 341,
 ' Subaru Forester': 342,
 ' Subaru Impreza': 343,
 ' Subaru Legacy': 344,
 ' Subaru Outback': 345,
 ' Subaru WRX': 346,
 ' Subaru XV Crosstrek': 347,
 ' Tesla Model ': 348,
 ' Tesla Model S': 349,
 ' Tesla Model X': 350,
 ' Tesla Model Y': 351,
 ' Toyota ': 352,
 ' Toyota Avalon': 353,
 ' Toyota C-HR': 354,
 ' Toyota Camry': 355,
 ' Toyota Camry Hybrid': 356,
 ' Toyota Corolla': 357,
 ' Toyota Corolla Cross': 358,
 ' Toyota Corolla Hatchback': 359,
 ' Toyota Corolla Hybrid': 360,
 ' Toyota Corolla iM': 361,
 ' Toyota FJ Cruiser': 362,
 ' Toyota GR': 363,
 ' Toyota GR Supra': 364,
 ' Toyota Highlander': 365,
 ' Toyota Highlander Hybrid': 366,
 ' Toyota Matrix': 367,
 ' Toyota Prius': 368,
 ' Toyota Prius Plug-in Hybrid': 369,
 ' Toyota Prius Prime': 370,
 ' Toyota Prius c': 371,
 ' Toyota Prius v': 372,
 ' Toyota RAV': 373,
 ' Toyota RAV Hybrid': 374,
 ' Toyota Runner': 375,
 ' Toyota Sequoia': 376,
 ' Toyota Sienna': 377,
 ' Toyota Tacoma Access Cab': 378,
 ' Toyota Tacoma Double Cab': 379,
 ' Toyota Tundra CrewMax': 380,
 ' Toyota Tundra Double Cab': 381,
 ' Toyota Tundra Hybrid CrewMax': 382,
 ' Toyota Venza': 383,
 ' Toyota Yaris': 384,
 ' Toyota Yaris Hatchback': 385,
 ' Toyota Yaris iA': 386,
 ' Volkswagen Atlas': 387,
 ' Volkswagen Atlas Cross Sport': 388,
 ' Volkswagen Beetle': 389,
 ' Volkswagen CC': 390,
 ' Volkswagen Eos': 391,
 ' Volkswagen GTI': 392,
 ' Volkswagen Golf': 393,
 ' Volkswagen Golf Alltrack': 394,
 ' Volkswagen Golf GTI': 395,
 ' Volkswagen Golf SportWagen': 396,
 ' Volkswagen ID.': 397,
 ' Volkswagen Jetta': 398,
 ' Volkswagen Jetta GLI': 399,
 ' Volkswagen Jetta SportWagen': 400,
 ' Volkswagen New Beetle': 401,
 ' Volkswagen Passat': 402,
 ' Volkswagen Routan': 403,
 ' Volkswagen Tiguan': 404,
 ' Volkswagen Tiguan Limited': 405,
 ' Volkswagen Touareg': 406,
 ' Volkswagen e-Golf': 407,
 ' Volvo C': 408,
 ' Volvo S': 409,
 ' Volvo V': 410,
 ' Volvo XC': 411,
 ' smart fortwo': 412,
 ' smart fortwo electric drive': 413,
 ' smart fortwo electric drive cabrio': 414,
 'Kia Sorento': 415}

stripped_mapping = {key.lstrip(): value for key, value in car_name_mapping.items() }

In [72]:
stripped_mapping

{'Acura ILX': 0,
 'Acura MDX': 1,
 'Acura MDX Sport Hybrid': 2,
 'Acura RDX': 3,
 'Acura RLX': 4,
 'Acura TL': 5,
 'Acura TLX': 6,
 'Acura TSX': 7,
 'Alfa Romeo C Spider': 8,
 'Alfa Romeo Giulia': 9,
 'Alfa Romeo Stelvio': 10,
 'Audi A': 11,
 'Audi A Sportback e-tron': 12,
 'Audi Q': 13,
 'Audi S': 14,
 'Audi TT': 15,
 'Audi allroad': 16,
 'Audi e-tron': 17,
 'BMW  Series': 18,
 'BMW M': 19,
 'BMW X': 20,
 'BMW Z': 21,
 'BMW i': 22,
 'Buick Cascada': 23,
 'Buick Enclave': 24,
 'Buick Encore': 25,
 'Buick Encore GX': 26,
 'Buick Envision': 27,
 'Buick LaCrosse': 28,
 'Buick Lucerne': 29,
 'Buick Regal': 30,
 'Buick Regal Sportback': 31,
 'Buick Verano': 32,
 'Cadillac ATS': 33,
 'Cadillac CT': 34,
 'Cadillac CTS': 35,
 'Cadillac DTS': 36,
 'Cadillac ELR': 37,
 'Cadillac Escalade ESV': 38,
 'Cadillac SRX': 39,
 'Cadillac XT': 40,
 'Cadillac XTS': 41,
 'Chevrolet Blazer': 42,
 'Chevrolet Bolt EV': 43,
 'Chevrolet Camaro': 44,
 'Chevrolet Captiva Sport': 45,
 'Chevrolet City Express': 46,
 'Chevrolet Colorado Crew Cab': 47,
 'Chevrolet Colorado Extended Cab': 48,
 'Chevrolet Corvette': 49,
 'Chevrolet Cruze': 50,
 'Chevrolet Cruze Limited': 51,
 'Chevrolet Equinox': 52,
 'Chevrolet Impala': 53,
 'Chevrolet Impala Limited': 54,
 'Chevrolet Malibu': 55,
 'Chevrolet Malibu Limited': 56,
 'Chevrolet Silverado  Crew Cab': 57,
 'Chevrolet Silverado  Double Cab': 58,
 'Chevrolet Silverado  HD Crew Cab': 59,
 'Chevrolet Silverado  HD Regular Cab': 60,
 'Chevrolet Silverado  Limited Crew Cab': 61,
 'Chevrolet Silverado  Regular Cab': 62,
 'Chevrolet Sonic': 63,
 'Chevrolet Spark': 64,
 'Chevrolet Spark EV': 65,
 'Chevrolet Suburban': 66,
 'Chevrolet Suburban ': 67,
 'Chevrolet Tahoe': 68,
 'Chevrolet Trailblazer': 69,
 'Chevrolet Traverse': 70,
 'Chevrolet Trax': 71,
 'Chevrolet Volt': 72,
 'Chrysler ': 73,
 'Chrysler Pacifica': 74,
 'Chrysler Sebring': 75,
 'Chrysler Town & Country': 76,
 'Chrysler Voyager': 77,
 'Dodge Avenger': 78,
 'Dodge Challenger': 79,
 'Dodge Charger': 80,
 'Dodge Dart': 81,
 'Dodge Durango': 82,
 'Dodge Grand Caravan Passenger': 83,
 'Dodge Journey': 84,
 'FIAT ': 85,
 'FIAT  Abarth': 86,
 'FIAT  Spider': 87,
 'FIAT L': 88,
 'FIAT X': 89,
 'FIAT c Abarth': 90,
 'Ford Bronco': 91,
 'Ford Bronco Sport': 92,
 'Ford C-MAX Energi': 93,
 'Ford C-MAX Hybrid': 94,
 'Ford EcoSport': 95,
 'Ford Edge': 96,
 'Ford Escape': 97,
 'Ford Expedition': 98,
 'Ford Expedition EL': 99,
 'Ford Expedition MAX': 100,
 'Ford Explorer': 101,
 'Ford F Lightning': 102,
 'Ford F Regular Cab': 103,
 'Ford F Super Cab': 104,
 'Ford F SuperCrew Cab': 105,
 'Ford Fiesta': 106,
 'Ford Flex': 107,
 'Ford Focus': 108,
 'Ford Focus ST': 109,
 'Ford Fusion': 110,
 'Ford Fusion Energi': 111,
 'Ford Maverick': 112,
 'Ford Mustang': 113,
 'Ford Mustang MACH-E': 114,
 'Ford Ranger SuperCrew': 115,
 'Ford Taurus': 116,
 'Ford Transit  Wagon': 117,
 'Ford Transit Connect Passenger': 118,
 'Ford Transit Connect Passenger Wagon': 119,
 'GMC Acadia': 120,
 'GMC Acadia Limited': 121,
 'GMC Canyon Crew Cab': 122,
 'GMC Sierra  Crew Cab': 123,
 'GMC Sierra  Double Cab': 124,
 'GMC Sierra  Limited Crew Cab': 125,
 'GMC Sierra  Regular Cab': 126,
 'GMC Terrain': 127,
 'GMC Yukon': 128,
 'GMC Yukon XL': 129,
 'GMC Yukon XL ': 130,
 'Genesis G': 131,
 'Honda Accord': 132,
 'Honda Accord Crosstour': 133,
 'Honda Accord Hybrid': 134,
 'Honda CR-V': 135,
 'Honda CR-V Hybrid': 136,
 'Honda CR-Z': 137,
 'Honda Civic': 138,
 'Honda Civic Type R': 139,
 'Honda Clarity Plug-in Hybrid': 140,
 'Honda Crosstour': 141,
 'Honda Fit': 142,
 'Honda HR-V': 143,
 'Honda Insight': 144,
 'Honda Odyssey': 145,
 'Honda Passport': 146,
 'Honda Pilot': 147,
 'Honda Ridgeline': 148,
 'Hyundai Accent': 149,
 'Hyundai Azera': 150,
 'Hyundai Elantra': 151,
 'Hyundai Elantra GT': 152,
 'Hyundai Equus': 153,
 'Hyundai Genesis': 154,
 'Hyundai Genesis Coupe': 155,
 'Hyundai IONIQ ': 156,
 'Hyundai Ioniq Electric': 157,
 'Hyundai Ioniq Hybrid': 158,
 'Hyundai Ioniq Plug-in Hybrid': 159,
 'Hyundai Kona': 160,
 'Hyundai Palisade': 161,
 'Hyundai Santa Cruz': 162,
 'Hyundai Santa Fe': 163,
 'Hyundai Santa Fe Sport': 164,
 'Hyundai Sonata': 165,
 'Hyundai Sonata Hybrid': 166,
 'Hyundai Sonata Plug-in Hybrid': 167,
 'Hyundai Tucson': 168,
 'Hyundai Tucson Hybrid': 169,
 'Hyundai Veloster': 170,
 'Hyundai Venue': 171,
 'Hyundai Veracruz': 172,
 'INFINITI EX': 173,
 'INFINITI FX': 174,
 'INFINITI G': 175,
 'INFINITI JX': 176,
 'INFINITI M': 177,
 'INFINITI Q': 178,
 'INFINITI QX': 179,
 'Jaguar E-PACE': 180,
 'Jaguar F-PACE': 181,
 'Jaguar F-TYPE': 182,
 'Jaguar XE': 183,
 'Jaguar XF': 184,
 'Jaguar XJ': 185,
 'Jeep Cherokee': 186,
 'Jeep Compass': 187,
 'Jeep Gladiator': 188,
 'Jeep Grand Cherokee': 189,
 'Jeep Grand Cherokee L': 190,
 'Jeep Liberty': 191,
 'Jeep Patriot': 192,
 'Jeep Renegade': 193,
 'Jeep Wagoneer': 194,
 'Jeep Wrangler': 195,
 'Jeep Wrangler Unlimited': 196,
 'Kia Cadenza': 197,
 'Kia Carnival': 198,
 'Kia EV': 199,
 'Kia Forte': 200,
 'Kia Forte Koup': 201,
 'Kia K': 202,
 'Kia Niro': 203,
 'Kia Niro EV': 204,
 'Kia Optima': 205,
 'Kia Optima Hybrid': 206,
 'Kia Rio': 207,
 'Kia Sedona': 208,
 'Kia Seltos': 209,
 'Kia Sorento': 415,
 'Kia Sorento Hybrid': 211,
 'Kia Sorento Plug-in Hybrid': 212,
 'Kia Soul': 213,
 'Kia Soul EV': 214,
 'Kia Sportage': 215,
 'Kia Stinger': 216,
 'Kia Telluride': 217,
 'Land Rover Discovery': 218,
 'Land Rover Discovery Sport': 219,
 'Land Rover LR': 220,
 'Land Rover Range Rover': 221,
 'Land Rover Range Rover Evoque': 222,
 'Land Rover Range Rover Sport': 223,
 'Land Rover Range Rover Velar': 224,
 'Lexus CT': 225,
 'Lexus ES': 226,
 'Lexus GS': 227,
 'Lexus GX': 228,
 'Lexus HS': 229,
 'Lexus IS': 230,
 'Lexus LC': 231,
 'Lexus LS': 232,
 'Lexus NX': 233,
 'Lexus RC': 234,
 'Lexus RX': 235,
 'Lexus UX': 236,
 'Lincoln Corsair': 237,
 'Lincoln MKC': 238,
 'Lincoln MKS': 239,
 'Lincoln MKX': 240,
 'Lincoln MKZ': 241,
 'Lincoln Nautilus': 242,
 'Lincoln Navigator': 243,
 'Lincoln Town Car': 244,
 'MAZDA CX-': 245,
 'MAZDA MAZDA': 246,
 'MAZDA MX- Miata': 247,
 'MAZDA MX- Miata RF': 248,
 'MAZDA Tribute': 249,
 'MINI Clubman': 250,
 'MINI Convertible': 251,
 'MINI Countryman': 252,
 'MINI Coupe': 253,
 'MINI Hardtop': 254,
 'MINI Hardtop  Door': 255,
 'MINI Paceman': 256,
 'MINI Roadster': 257,
 'Maserati Ghibli': 258,
 'Maserati GranTurismo': 259,
 'Maserati Levante': 260,
 'Maserati Quattroporte': 261,
 'Mercedes-Benz A-Class': 262,
 'Mercedes-Benz B-Class': 263,
 'Mercedes-Benz C-Class': 264,
 'Mercedes-Benz CLA': 265,
 'Mercedes-Benz CLA-Class': 266,
 'Mercedes-Benz CLK-Class': 267,
 'Mercedes-Benz CLS-Class': 268,
 'Mercedes-Benz E-Class': 269,
 'Mercedes-Benz GLA': 270,
 'Mercedes-Benz GLA-Class': 271,
 'Mercedes-Benz GLB': 272,
 'Mercedes-Benz GLC': 273,
 'Mercedes-Benz GLE': 274,
 'Mercedes-Benz GLK-Class': 275,
 'Mercedes-Benz GLS': 276,
 'Mercedes-Benz M-Class': 277,
 'Mercedes-Benz Mercedes-AMG C-Class': 278,
 'Mercedes-Benz Mercedes-AMG GLC': 279,
 'Mercedes-Benz Mercedes-AMG GLE Coupe': 280,
 'Mercedes-Benz Mercedes-AMG SLC': 281,
 'Mercedes-Benz R-Class': 282,
 'Mercedes-Benz S-Class': 283,
 'Mercedes-Benz SL': 284,
 'Mercedes-Benz SL-Class': 285,
 'Mercedes-Benz SLC': 286,
 'Mercedes-Benz SLK-Class': 287,
 'Mitsubishi Eclipse Cross': 288,
 'Mitsubishi Lancer': 289,
 'Mitsubishi Mirage': 290,
 'Mitsubishi Mirage G': 291,
 'Mitsubishi Outlander': 292,
 'Mitsubishi Outlander PHEV': 293,
 'Mitsubishi Outlander Sport': 294,
 'Mitsubishi i-MiEV': 295,
 'Nissan Altima': 296,
 'Nissan Armada': 297,
 'Nissan Frontier Crew Cab': 298,
 'Nissan Frontier King Cab': 299,
 'Nissan JUKE': 300,
 'Nissan Kicks': 301,
 'Nissan LEAF': 302,
 'Nissan Maxima': 303,
 'Nissan Murano': 304,
 'Nissan Pathfinder': 305,
 'Nissan Quest': 306,
 'Nissan Rogue': 307,
 'Nissan Rogue Select': 308,
 'Nissan Rogue Sport': 309,
 'Nissan Sentra': 310,
 'Nissan TITAN XD Crew Cab': 311,
 'Nissan Titan Crew Cab': 312,
 'Nissan Versa': 313,
 'Nissan Versa Note': 314,
 'Nissan Xterra': 315,
 'Nissan Z': 316,
 'Polestar ': 317,
 'Pontiac Solstice': 318,
 'Porsche ': 319,
 'Porsche  Cayman': 320,
 'Porsche Boxster': 321,
 'Porsche Cayenne': 322,
 'Porsche Macan': 323,
 'Porsche Panamera': 324,
 'Ram  Classic Crew Cab': 325,
 'Ram  Classic Quad Cab': 326,
 'Ram  Classic Regular Cab': 327,
 'Ram  Crew Cab': 328,
 'Ram  Quad Cab': 329,
 'Ram  Regular Cab': 330,
 'Saturn SKY': 331,
 'Scion FR-S': 332,
 'Scion iA': 333,
 'Scion iM': 334,
 'Scion iQ': 335,
 'Scion tC': 336,
 'Scion xB': 337,
 'Scion xD': 338,
 'Subaru Ascent': 339,
 'Subaru BRZ': 340,
 'Subaru Crosstrek': 341,
 'Subaru Forester': 342,
 'Subaru Impreza': 343,
 'Subaru Legacy': 344,
 'Subaru Outback': 345,
 'Subaru WRX': 346,
 'Subaru XV Crosstrek': 347,
 'Tesla Model ': 348,
 'Tesla Model S': 349,
 'Tesla Model X': 350,
 'Tesla Model Y': 351,
 'Toyota ': 352,
 'Toyota Avalon': 353,
 'Toyota C-HR': 354,
 'Toyota Camry': 355,
 'Toyota Camry Hybrid': 356,
 'Toyota Corolla': 357,
 'Toyota Corolla Cross': 358,
 'Toyota Corolla Hatchback': 359,
 'Toyota Corolla Hybrid': 360,
 'Toyota Corolla iM': 361,
 'Toyota FJ Cruiser': 362,
 'Toyota GR': 363,
 'Toyota GR Supra': 364,
 'Toyota Highlander': 365,
 'Toyota Highlander Hybrid': 366,
 'Toyota Matrix': 367,
 'Toyota Prius': 368,
 'Toyota Prius Plug-in Hybrid': 369,
 'Toyota Prius Prime': 370,
 'Toyota Prius c': 371,
 'Toyota Prius v': 372,
 'Toyota RAV': 373,
 'Toyota RAV Hybrid': 374,
 'Toyota Runner': 375,
 'Toyota Sequoia': 376,
 'Toyota Sienna': 377,
 'Toyota Tacoma Access Cab': 378,
 'Toyota Tacoma Double Cab': 379,
 'Toyota Tundra CrewMax': 380,
 'Toyota Tundra Double Cab': 381,
 'Toyota Tundra Hybrid CrewMax': 382,
 'Toyota Venza': 383,
 'Toyota Yaris': 384,
 'Toyota Yaris Hatchback': 385,
 'Toyota Yaris iA': 386,
 'Volkswagen Atlas': 387,
 'Volkswagen Atlas Cross Sport': 388,
 'Volkswagen Beetle': 389,
 'Volkswagen CC': 390,
 'Volkswagen Eos': 391,
 'Volkswagen GTI': 392,
 'Volkswagen Golf': 393,
 'Volkswagen Golf Alltrack': 394,
 'Volkswagen Golf GTI': 395,
 'Volkswagen Golf SportWagen': 396,
 'Volkswagen ID.': 397,
 'Volkswagen Jetta': 398,
 'Volkswagen Jetta GLI': 399,
 'Volkswagen Jetta SportWagen': 400,
 'Volkswagen New Beetle': 401,
 'Volkswagen Passat': 402,
 'Volkswagen Routan': 403,
 'Volkswagen Tiguan': 404,
 'Volkswagen Tiguan Limited': 405,
 'Volkswagen Touareg': 406,
 'Volkswagen e-Golf': 407,
 'Volvo C': 408,
 'Volvo S': 409,
 'Volvo V': 410,
 'Volvo XC': 411,
 'smart fortwo': 412,
 'smart fortwo electric drive': 413,
 'smart fortwo electric drive cabrio': 414}

In [73]:
clean_mapping = {str(k): int(v) for k, v in stripped_mapping.items()}

In [75]:
clean_mapping

{'Acura ILX': 0,
 'Acura MDX': 1,
 'Acura MDX Sport Hybrid': 2,
 'Acura RDX': 3,
 'Acura RLX': 4,
 'Acura TL': 5,
 'Acura TLX': 6,
 'Acura TSX': 7,
 'Alfa Romeo C Spider': 8,
 'Alfa Romeo Giulia': 9,
 'Alfa Romeo Stelvio': 10,
 'Audi A': 11,
 'Audi A Sportback e-tron': 12,
 'Audi Q': 13,
 'Audi S': 14,
 'Audi TT': 15,
 'Audi allroad': 16,
 'Audi e-tron': 17,
 'BMW  Series': 18,
 'BMW M': 19,
 'BMW X': 20,
 'BMW Z': 21,
 'BMW i': 22,
 'Buick Cascada': 23,
 'Buick Enclave': 24,
 'Buick Encore': 25,
 'Buick Encore GX': 26,
 'Buick Envision': 27,
 'Buick LaCrosse': 28,
 'Buick Lucerne': 29,
 'Buick Regal': 30,
 'Buick Regal Sportback': 31,
 'Buick Verano': 32,
 'Cadillac ATS': 33,
 'Cadillac CT': 34,
 'Cadillac CTS': 35,
 'Cadillac DTS': 36,
 'Cadillac ELR': 37,
 'Cadillac Escalade ESV': 38,
 'Cadillac SRX': 39,
 'Cadillac XT': 40,
 'Cadillac XTS': 41,
 'Chevrolet Blazer': 42,
 'Chevrolet Bolt EV': 43,
 'Chevrolet Camaro': 44,
 'Chevrolet Captiva Sport': 45,
 'Chevrolet City Express': 46,
 'Chevrolet Colorado Crew Cab': 47,
 'Chevrolet Colorado Extended Cab': 48,
 'Chevrolet Corvette': 49,
 'Chevrolet Cruze': 50,
 'Chevrolet Cruze Limited': 51,
 'Chevrolet Equinox': 52,
 'Chevrolet Impala': 53,
 'Chevrolet Impala Limited': 54,
 'Chevrolet Malibu': 55,
 'Chevrolet Malibu Limited': 56,
 'Chevrolet Silverado  Crew Cab': 57,
 'Chevrolet Silverado  Double Cab': 58,
 'Chevrolet Silverado  HD Crew Cab': 59,
 'Chevrolet Silverado  HD Regular Cab': 60,
 'Chevrolet Silverado  Limited Crew Cab': 61,
 'Chevrolet Silverado  Regular Cab': 62,
 'Chevrolet Sonic': 63,
 'Chevrolet Spark': 64,
 'Chevrolet Spark EV': 65,
 'Chevrolet Suburban': 66,
 'Chevrolet Suburban ': 67,
 'Chevrolet Tahoe': 68,
 'Chevrolet Trailblazer': 69,
 'Chevrolet Traverse': 70,
 'Chevrolet Trax': 71,
 'Chevrolet Volt': 72,
 'Chrysler ': 73,
 'Chrysler Pacifica': 74,
 'Chrysler Sebring': 75,
 'Chrysler Town & Country': 76,
 'Chrysler Voyager': 77,
 'Dodge Avenger': 78,
 'Dodge Challenger': 79,
 'Dodge Charger': 80,
 'Dodge Dart': 81,
 'Dodge Durango': 82,
 'Dodge Grand Caravan Passenger': 83,
 'Dodge Journey': 84,
 'FIAT ': 85,
 'FIAT  Abarth': 86,
 'FIAT  Spider': 87,
 'FIAT L': 88,
 'FIAT X': 89,
 'FIAT c Abarth': 90,
 'Ford Bronco': 91,
 'Ford Bronco Sport': 92,
 'Ford C-MAX Energi': 93,
 'Ford C-MAX Hybrid': 94,
 'Ford EcoSport': 95,
 'Ford Edge': 96,
 'Ford Escape': 97,
 'Ford Expedition': 98,
 'Ford Expedition EL': 99,
 'Ford Expedition MAX': 100,
 'Ford Explorer': 101,
 'Ford F Lightning': 102,
 'Ford F Regular Cab': 103,
 'Ford F Super Cab': 104,
 'Ford F SuperCrew Cab': 105,
 'Ford Fiesta': 106,
 'Ford Flex': 107,
 'Ford Focus': 108,
 'Ford Focus ST': 109,
 'Ford Fusion': 110,
 'Ford Fusion Energi': 111,
 'Ford Maverick': 112,
 'Ford Mustang': 113,
 'Ford Mustang MACH-E': 114,
 'Ford Ranger SuperCrew': 115,
 'Ford Taurus': 116,
 'Ford Transit  Wagon': 117,
 'Ford Transit Connect Passenger': 118,
 'Ford Transit Connect Passenger Wagon': 119,
 'GMC Acadia': 120,
 'GMC Acadia Limited': 121,
 'GMC Canyon Crew Cab': 122,
 'GMC Sierra  Crew Cab': 123,
 'GMC Sierra  Double Cab': 124,
 'GMC Sierra  Limited Crew Cab': 125,
 'GMC Sierra  Regular Cab': 126,
 'GMC Terrain': 127,
 'GMC Yukon': 128,
 'GMC Yukon XL': 129,
 'GMC Yukon XL ': 130,
 'Genesis G': 131,
 'Honda Accord': 132,
 'Honda Accord Crosstour': 133,
 'Honda Accord Hybrid': 134,
 'Honda CR-V': 135,
 'Honda CR-V Hybrid': 136,
 'Honda CR-Z': 137,
 'Honda Civic': 138,
 'Honda Civic Type R': 139,
 'Honda Clarity Plug-in Hybrid': 140,
 'Honda Crosstour': 141,
 'Honda Fit': 142,
 'Honda HR-V': 143,
 'Honda Insight': 144,
 'Honda Odyssey': 145,
 'Honda Passport': 146,
 'Honda Pilot': 147,
 'Honda Ridgeline': 148,
 'Hyundai Accent': 149,
 'Hyundai Azera': 150,
 'Hyundai Elantra': 151,
 'Hyundai Elantra GT': 152,
 'Hyundai Equus': 153,
 'Hyundai Genesis': 154,
 'Hyundai Genesis Coupe': 155,
 'Hyundai IONIQ ': 156,
 'Hyundai Ioniq Electric': 157,
 'Hyundai Ioniq Hybrid': 158,
 'Hyundai Ioniq Plug-in Hybrid': 159,
 'Hyundai Kona': 160,
 'Hyundai Palisade': 161,
 'Hyundai Santa Cruz': 162,
 'Hyundai Santa Fe': 163,
 'Hyundai Santa Fe Sport': 164,
 'Hyundai Sonata': 165,
 'Hyundai Sonata Hybrid': 166,
 'Hyundai Sonata Plug-in Hybrid': 167,
 'Hyundai Tucson': 168,
 'Hyundai Tucson Hybrid': 169,
 'Hyundai Veloster': 170,
 'Hyundai Venue': 171,
 'Hyundai Veracruz': 172,
 'INFINITI EX': 173,
 'INFINITI FX': 174,
 'INFINITI G': 175,
 'INFINITI JX': 176,
 'INFINITI M': 177,
 'INFINITI Q': 178,
 'INFINITI QX': 179,
 'Jaguar E-PACE': 180,
 'Jaguar F-PACE': 181,
 'Jaguar F-TYPE': 182,
 'Jaguar XE': 183,
 'Jaguar XF': 184,
 'Jaguar XJ': 185,
 'Jeep Cherokee': 186,
 'Jeep Compass': 187,
 'Jeep Gladiator': 188,
 'Jeep Grand Cherokee': 189,
 'Jeep Grand Cherokee L': 190,
 'Jeep Liberty': 191,
 'Jeep Patriot': 192,
 'Jeep Renegade': 193,
 'Jeep Wagoneer': 194,
 'Jeep Wrangler': 195,
 'Jeep Wrangler Unlimited': 196,
 'Kia Cadenza': 197,
 'Kia Carnival': 198,
 'Kia EV': 199,
 'Kia Forte': 200,
 'Kia Forte Koup': 201,
 'Kia K': 202,
 'Kia Niro': 203,
 'Kia Niro EV': 204,
 'Kia Optima': 205,
 'Kia Optima Hybrid': 206,
 'Kia Rio': 207,
 'Kia Sedona': 208,
 'Kia Seltos': 209,
 'Kia Sorento': 415,
 'Kia Sorento Hybrid': 211,
 'Kia Sorento Plug-in Hybrid': 212,
 'Kia Soul': 213,
 'Kia Soul EV': 214,
 'Kia Sportage': 215,
 'Kia Stinger': 216,
 'Kia Telluride': 217,
 'Land Rover Discovery': 218,
 'Land Rover Discovery Sport': 219,
 'Land Rover LR': 220,
 'Land Rover Range Rover': 221,
 'Land Rover Range Rover Evoque': 222,
 'Land Rover Range Rover Sport': 223,
 'Land Rover Range Rover Velar': 224,
 'Lexus CT': 225,
 'Lexus ES': 226,
 'Lexus GS': 227,
 'Lexus GX': 228,
 'Lexus HS': 229,
 'Lexus IS': 230,
 'Lexus LC': 231,
 'Lexus LS': 232,
 'Lexus NX': 233,
 'Lexus RC': 234,
 'Lexus RX': 235,
 'Lexus UX': 236,
 'Lincoln Corsair': 237,
 'Lincoln MKC': 238,
 'Lincoln MKS': 239,
 'Lincoln MKX': 240,
 'Lincoln MKZ': 241,
 'Lincoln Nautilus': 242,
 'Lincoln Navigator': 243,
 'Lincoln Town Car': 244,
 'MAZDA CX-': 245,
 'MAZDA MAZDA': 246,
 'MAZDA MX- Miata': 247,
 'MAZDA MX- Miata RF': 248,
 'MAZDA Tribute': 249,
 'MINI Clubman': 250,
 'MINI Convertible': 251,
 'MINI Countryman': 252,
 'MINI Coupe': 253,
 'MINI Hardtop': 254,
 'MINI Hardtop  Door': 255,
 'MINI Paceman': 256,
 'MINI Roadster': 257,
 'Maserati Ghibli': 258,
 'Maserati GranTurismo': 259,
 'Maserati Levante': 260,
 'Maserati Quattroporte': 261,
 'Mercedes-Benz A-Class': 262,
 'Mercedes-Benz B-Class': 263,
 'Mercedes-Benz C-Class': 264,
 'Mercedes-Benz CLA': 265,
 'Mercedes-Benz CLA-Class': 266,
 'Mercedes-Benz CLK-Class': 267,
 'Mercedes-Benz CLS-Class': 268,
 'Mercedes-Benz E-Class': 269,
 'Mercedes-Benz GLA': 270,
 'Mercedes-Benz GLA-Class': 271,
 'Mercedes-Benz GLB': 272,
 'Mercedes-Benz GLC': 273,
 'Mercedes-Benz GLE': 274,
 'Mercedes-Benz GLK-Class': 275,
 'Mercedes-Benz GLS': 276,
 'Mercedes-Benz M-Class': 277,
 'Mercedes-Benz Mercedes-AMG C-Class': 278,
 'Mercedes-Benz Mercedes-AMG GLC': 279,
 'Mercedes-Benz Mercedes-AMG GLE Coupe': 280,
 'Mercedes-Benz Mercedes-AMG SLC': 281,
 'Mercedes-Benz R-Class': 282,
 'Mercedes-Benz S-Class': 283,
 'Mercedes-Benz SL': 284,
 'Mercedes-Benz SL-Class': 285,
 'Mercedes-Benz SLC': 286,
 'Mercedes-Benz SLK-Class': 287,
 'Mitsubishi Eclipse Cross': 288,
 'Mitsubishi Lancer': 289,
 'Mitsubishi Mirage': 290,
 'Mitsubishi Mirage G': 291,
 'Mitsubishi Outlander': 292,
 'Mitsubishi Outlander PHEV': 293,
 'Mitsubishi Outlander Sport': 294,
 'Mitsubishi i-MiEV': 295,
 'Nissan Altima': 296,
 'Nissan Armada': 297,
 'Nissan Frontier Crew Cab': 298,
 'Nissan Frontier King Cab': 299,
 'Nissan JUKE': 300,
 'Nissan Kicks': 301,
 'Nissan LEAF': 302,
 'Nissan Maxima': 303,
 'Nissan Murano': 304,
 'Nissan Pathfinder': 305,
 'Nissan Quest': 306,
 'Nissan Rogue': 307,
 'Nissan Rogue Select': 308,
 'Nissan Rogue Sport': 309,
 'Nissan Sentra': 310,
 'Nissan TITAN XD Crew Cab': 311,
 'Nissan Titan Crew Cab': 312,
 'Nissan Versa': 313,
 'Nissan Versa Note': 314,
 'Nissan Xterra': 315,
 'Nissan Z': 316,
 'Polestar ': 317,
 'Pontiac Solstice': 318,
 'Porsche ': 319,
 'Porsche  Cayman': 320,
 'Porsche Boxster': 321,
 'Porsche Cayenne': 322,
 'Porsche Macan': 323,
 'Porsche Panamera': 324,
 'Ram  Classic Crew Cab': 325,
 'Ram  Classic Quad Cab': 326,
 'Ram  Classic Regular Cab': 327,
 'Ram  Crew Cab': 328,
 'Ram  Quad Cab': 329,
 'Ram  Regular Cab': 330,
 'Saturn SKY': 331,
 'Scion FR-S': 332,
 'Scion iA': 333,
 'Scion iM': 334,
 'Scion iQ': 335,
 'Scion tC': 336,
 'Scion xB': 337,
 'Scion xD': 338,
 'Subaru Ascent': 339,
 'Subaru BRZ': 340,
 'Subaru Crosstrek': 341,
 'Subaru Forester': 342,
 'Subaru Impreza': 343,
 'Subaru Legacy': 344,
 'Subaru Outback': 345,
 'Subaru WRX': 346,
 'Subaru XV Crosstrek': 347,
 'Tesla Model ': 348,
 'Tesla Model S': 349,
 'Tesla Model X': 350,
 'Tesla Model Y': 351,
 'Toyota ': 352,
 'Toyota Avalon': 353,
 'Toyota C-HR': 354,
 'Toyota Camry': 355,
 'Toyota Camry Hybrid': 356,
 'Toyota Corolla': 357,
 'Toyota Corolla Cross': 358,
 'Toyota Corolla Hatchback': 359,
 'Toyota Corolla Hybrid': 360,
 'Toyota Corolla iM': 361,
 'Toyota FJ Cruiser': 362,
 'Toyota GR': 363,
 'Toyota GR Supra': 364,
 'Toyota Highlander': 365,
 'Toyota Highlander Hybrid': 366,
 'Toyota Matrix': 367,
 'Toyota Prius': 368,
 'Toyota Prius Plug-in Hybrid': 369,
 'Toyota Prius Prime': 370,
 'Toyota Prius c': 371,
 'Toyota Prius v': 372,
 'Toyota RAV': 373,
 'Toyota RAV Hybrid': 374,
 'Toyota Runner': 375,
 'Toyota Sequoia': 376,
 'Toyota Sienna': 377,
 'Toyota Tacoma Access Cab': 378,
 'Toyota Tacoma Double Cab': 379,
 'Toyota Tundra CrewMax': 380,
 'Toyota Tundra Double Cab': 381,
 'Toyota Tundra Hybrid CrewMax': 382,
 'Toyota Venza': 383,
 'Toyota Yaris': 384,
 'Toyota Yaris Hatchback': 385,
 'Toyota Yaris iA': 386,
 'Volkswagen Atlas': 387,
 'Volkswagen Atlas Cross Sport': 388,
 'Volkswagen Beetle': 389,
 'Volkswagen CC': 390,
 'Volkswagen Eos': 391,
 'Volkswagen GTI': 392,
 'Volkswagen Golf': 393,
 'Volkswagen Golf Alltrack': 394,
 'Volkswagen Golf GTI': 395,
 'Volkswagen Golf SportWagen': 396,
 'Volkswagen ID.': 397,
 'Volkswagen Jetta': 398,
 'Volkswagen Jetta GLI': 399,
 'Volkswagen Jetta SportWagen': 400,
 'Volkswagen New Beetle': 401,
 'Volkswagen Passat': 402,
 'Volkswagen Routan': 403,
 'Volkswagen Tiguan': 404,
 'Volkswagen Tiguan Limited': 405,
 'Volkswagen Touareg': 406,
 'Volkswagen e-Golf': 407,
 'Volvo C': 408,
 'Volvo S': 409,
 'Volvo V': 410,
 'Volvo XC': 411,
 'smart fortwo': 412,
 'smart fortwo electric drive': 413,
 'smart fortwo electric drive cabrio': 414}

In [76]:
import json

In [78]:
with open("car_name_mapping.json", "w") as file_object:
    json.dump(clean_mapping, file_object, indent=4)